apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: webapp-prod
data:
  NODE_ENV: "production"
  PORT: "3000"
  FRONTEND_URL: "http://bmi-web.local" # replace with your real host
  DB_NAME: "bmidb"
  DB_HOST: "bmi-db"
  DB_PORT: "5432"
